site_name: EHRCON26 Clinical Modelling Workshop
theme:
    name: material
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: lightblue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: lightblue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode